# Generated by Django 4.1.2 on 2022-11-19 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_alter_post_likes_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='related_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='network.post'),
        ),
    ]
